<a href="https://colab.research.google.com/github/Meeradileep/new_jango/blob/main/Project_cafesales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
name1 = input("Enter your name ")
name2 = input("Enter his or her name ")
score = random.randint(0,100)
print(f"\n love between {name1} and {name2} is {score}%")
if score < 35:
  print ("no chance")
elif (score >= 35 and score < 50) :
  print ("Fine")

elif (score >=50 and score < 80):
  print("Perfect match")

else:
  print("fixed marrage")

In [3]:
print("Welcome to Reva ATH")

balance=0

pin = int(input("Set the pin"))

entred_pin = int(input("Enter your pin to contiune"))

if(entred_pin == pin):
  print("Login Successfull")

while True:
  print("1.Deposit")
  print("2.Check Balanace")
  print("3.WithDraw")
  print("4.Exit")

  choice= int(input("Enter your choice"))

  if choice==1:
             amount = int(input("Enter the amount to Deposite"))
             balance += amount
             print("Money Deposited")

  elif choice==2:
             print("Your balance is", balance)
  elif(choice ==3):
    amount =int(input("Enter amount to withdraw:  "))
    if amount<=balance:
      balance -= amount
      print("Please collect your cash!")
    else:
      print("Insufficient balance!")

  elif choice == 4:
      print(" Thank you for using ATM")
      break

  else:
    print("Invalide Choice")

else:
  print("Wrong pin")

Welcome to Reva ATH
Set the pin1250
Enter your pin to contiune1250
Login Successfull
1.Deposit
2.Check Balanace
3.WithDraw
4.Exit
Enter your choice2
Your balance is 0
1.Deposit
2.Check Balanace
3.WithDraw
4.Exit
Enter your choice1


KeyboardInterrupt: Interrupted by user

  NUMPY--Numerical
  python

  uses of numpy
  arithematical operation

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
arr = np.array([[1,2],[3,4],[4,5]])
print(arr)

[[1 2]
 [3 4]
 [4 5]]


In [6]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr = np.ones((2,3))*5
print(arr)

[[5. 5. 5.]
 [5. 5. 5.]]


In [9]:
arr = np.arange(5,15,2)
print(arr)

[ 5  7  9 11 13]


In [13]:
arr = np.eye(3)*4
print(arr)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


In [19]:
arr=np.arange(1,300,2)
print(arr)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299]


In [21]:
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [22]:
arr=np.random.random((2,3))
print(arr)

[[0.82331852 0.46392674 0.52391366]
 [0.72628699 0.89997681 0.69095144]]


In [24]:
arr=np.random.randint(1,100,(2,3))
print(arr)

[[22 12 56]
 [50 36 86]]


In [26]:
import numpy as np
marks = np.array([45,78,56,99,10])
print("Marks:",marks)
print("Lowest Marks:",np.min(marks))
print("Highest Marks:",np.max(marks))
print("Average Marks:",np.mean(marks))
print("Greated than 70:",marks[marks>70])

Marks: [45 78 56 99 10]
Lowest Marks: 10
Highest Marks: 99
Average Marks: 57.6
Greated than 70: [78 99]


In [30]:
1500, 2300, 1800, 2700, 3200, 2100
import numpy as np
sales=np.array([1500,2300,1800,2700,3200,2100])
print("Sales:",sales)
print("Lowest sales:",np.min(sales))
print("Highest sales:",np.max(sales))
print("total sales:",np.mean(sales))
print("Less than 2000", sales[sales>2000])

Sales: [1500 2300 1800 2700 3200 2100]
Lowest sales: 1500
Highest sales: 3200
total sales: 2266.6666666666665
Less than 2000 [2300 2700 3200 2100]


In [37]:
import pandas as pd


In [38]:
data = {
    "Name":["Lavanya","Meera","Mehak","Keerthana"],
    "Age":["55","21","34","31"],
    "Place":["Bangalore","kerala","Maharastra","Mysore"],
    "Grand-Child":["Anvi","Vanshik","len","guvika"]
}
df = pd.DataFrame(data)
print(df)

        Name Age       Place Grand-Child
0    Lavanya  55   Bangalore        Anvi
1      Meera  21      kerala     Vanshik
2      Mehak  34  Maharastra         len
3  Keerthana  31      Mysore      guvika


In [40]:
df=pd.read_excel("cafesales.xlsx")
print(df.head())

   Order ID       Date             Product  Price    Quantity Purchase Type  \
0     10452 2022-11-07               Fries   3.49  573.065903       Online    
1     10453 2022-11-07           Beverages   2.95  745.762712       Online    
2     10454 2022-11-07       Sides & Other   4.99  200.400802     In-store    
3     10455 2022-11-08             Burgers  12.99  569.668976     In-store    
4     10456 2022-11-08  Chicken Sandwiches   9.95  201.005025     In-store    

  Payment Method    City        Manager  
0      Gift Card  London    Tom Jackson  
1      Gift Card  Madrid    Pablo Perez  
2      Gift Card  Lisbon     Joao Silva  
3    Credit Card  Berlin  Walter Muller  
4    Credit Card  Berlin  Walter Muller  


In [41]:
print(df.tail())

     Order ID       Date             Product  Price    Quantity Purchase Type  \
257     10709 2022-12-28       Sides & Other   4.99  200.400802   Drive-thru    
258     10710 2022-12-29             Burgers  12.99  754.426482   Drive-thru    
259     10711 2022-12-29  Chicken Sandwiches   9.95  281.407035   Drive-thru    
260     10712 2022-12-29               Fries   3.49  630.372493   Drive-thru    
261     10713 2022-12-29           Beverages   2.95  677.966102   Drive-thru    

    Payment Method    City        Manager  
257      Gift Card  Berlin  Walter Muller  
258      Gift Card  Berlin  Walter Muller  
259      Gift Card  Berlin  Walter Muller  
260      Gift Card  Berlin  Walter Muller  
261      Gift Card  Berlin  Walter Muller  


In [42]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Order ID        262 non-null    int64         
 1   Date            262 non-null    datetime64[ns]
 2   Product         262 non-null    object        
 3   Price           262 non-null    float64       
 4   Quantity        262 non-null    float64       
 5   Purchase Type   262 non-null    object        
 6   Payment Method  262 non-null    object        
 7   City            262 non-null    object        
 8   Manager         262 non-null    object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 18.6+ KB
None


In [43]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Order ID        262 non-null    int64         
 1   Date            262 non-null    datetime64[ns]
 2   Product         262 non-null    object        
 3   Price           262 non-null    float64       
 4   Quantity        262 non-null    float64       
 5   Purchase Type   262 non-null    object        
 6   Payment Method  262 non-null    object        
 7   City            262 non-null    object        
 8   Manager         262 non-null    object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 18.6+ KB
None


In [44]:
print(df.describe())

           Order ID                           Date       Price    Quantity
count    262.000000                            262  262.000000  262.000000
mean   10581.530534  2022-12-02 21:48:05.496183296    7.269122  462.688900
min    10452.000000            2022-11-07 00:00:00    2.950000  200.400802
25%    10514.250000            2022-11-19 06:00:00    3.490000  201.005025
50%    10579.500000            2022-12-02 12:00:00    4.990000  546.574288
75%    10647.750000            2022-12-16 00:00:00    9.950000  677.444188
max    10713.000000            2022-12-29 00:00:00   33.220000  754.426482
std       76.348998                            NaN    4.854682  214.765446
